# Generated by Django 4.0.1 on 2023-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_alter_patient_dateofbirth_alter_patient_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobileNumber',
            field=models.CharField(max_length=13, verbose_name='Mobile Number'),
        ),
    ]
